# Generated by Django 4.2.11 on 2024-05-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
